### ISSUE TITLE
如何缩短path自动生成的特长请求名？

### ISSUE THREAD

**Issue by akan** [e-kit/ekit#2]
adminServiceTicketMessageInfoInboxPageListPost
/admin/serviceTicket/messageInfo/inbox/pageList
其实希望这个path生成messageInfoInboxPageListPost。
这是需要改自己修改npm包，修改模版吗？

**Comment by gogoyqj** [comment]
如下配置即可：
```
{
  guardConfig: {
    prefixReg: /^\/admin\/serviceTicket/g
  }
}
```

@akan 

https://github.com/gogoyqj/auto-service

**Comment by akan** [comment]
![image](https://user-images.githubusercontent.com/170169/147431749-9957ca49-1b05-43f3-8c06-680e33fbc99e.png)
json模式下配置正则表达式不生效？
js模式也不生效？
![image](https://user-images.githubusercontent.com/170169/147432686-29e2994d-d17e-4cff-8051-8f1a1d44ee92.png)

**Comment by gogoyqj** [comment]
改成 json2service.js

**Comment by akan** [comment]
js模式也不生效？见上截图

**Comment by akan** [comment]
parseSwagger.ts parseSwagger
没有像guard.ts在operationIdGuard那样做处理。

**Comment by gogoyqj** [comment]
确实，，需要这么搞一下，删除本地已有的 swagger.json，然后修改 json2service.js 配置文件，添加：

```js
{
  swaggerConfig: {
   // 在 diff & patch 之前，变更远程 swagger
    modifier: swagger => {
      Object.keys(swagger.paths).forEach(url => {
        Object.keys(swagger.paths[url]).forEach(method => {
          swagger.paths[url][method].operationId = url;
        });
      });
      return swagger;
    }
  },
  guardConfig: {
    prefixReg: /^\/admin\/serviceTicket/g
  }
}
```

**Comment by gogoyqj** [comment]
> parseSwagger.ts parseSwagger 没有像guard.ts在operationIdGuard那样做处理。

确实，，需要这么搞一下，删除本地已有的 swagger.json，然后修改 json2service.js 配置文件，添加：

```js
{
  swaggerConfig: {
   // 在 diff & patch 之前，变更远程 swagger
    modifier: swagger => {
      Object.keys(swagger.paths).forEach(url => {
        Object.keys(swagger.paths[url]).forEach(method => {
          swagger.paths[url][method].operationId = url;
        });
      });
      return swagger;
    }
  },
  guardConfig: {
    prefixReg: /^\/admin\/serviceTicket/g
  }
}
```

@akan

**Comment by akan** [comment]
多谢。
目前_Api.ts部分ok了。不过model里面的还没有解决。
![image](https://user-images.githubusercontent.com/170169/147523468-91e5bea0-0ef7-46d2-804b-f41e878bdfca.png)

**Comment by akan** [comment]
我在想是不是修改yapi的配置会更有效。里面有什么basePath，然后后面的路径应该就变短了吧？
问了后端，据说yapi也是从swagger里面加载出来的。：（

**Comment by akan** [comment]
我修改api.json，忽略服务器端改动，解决了这个问题。api.json批量替换大法好使
